=== caterpillerGopher/gopher/gopher/src/main/java/gopher-data.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT gopher-data (suite | test-suite | test-class | test-data-type | test-case |
	test-data | element-locator | test-node | suite-decorator | test-suite-decorator | test-class-decorator |test-run | supported-browser)*>
<!ELEMENT suite (id, name, version, description?, runmode, test-suite-id*)>
<!ELEMENT test-suite (id, name, version, description?, runmode, test-class-id*)>
<!ELEMENT test-class (id, name, version, class-name, description?, runmode, jira-issue, test-data-type-id*)>
<!ELEMENT test-data-type (id, name, type, role)>
<!ELEMENT test-data (id, value, test-data-type-id)>
<!ELEMENT element-locator (id, locator-type, name, value, description?)>
<!ELEMENT test-case (id, name, version, runmode, test-class-id, test-data-id*, element-locator-id*)>
<!ELEMENT suite-decorator (id, name, url?, browser?, runmode, suite-id)>
<!ELEMENT test-run (id, url?, browser?, runmode, test-case-id, test-node-id?)>
<!ELEMENT test-suite-decorator (id, url?, browser?, runmode, suite-id, test-suite-id)>
<!ELEMENT test-class-decorator (id, url?, browser?, runmode, test-suite-id, test-class-id)>
<!ELEMENT test-node (id, node-ip?, node-port, platform, user-name, password?,
install-dir, selenium-server, supported-browser-id*)>
<!ELEMENT supported-browser (id, name, browser-type)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT test-class-id (#PCDATA)>
<!ELEMENT test-case-id (#PCDATA)>
<!ELEMENT test-run-id (#PCDATA)>
<!ELEMENT test-node-id (#PCDATA)>
<!ELEMENT test-data-type-id (#PCDATA)>
<!ELEMENT test-data-id (#PCDATA)>
<!ELEMENT element-locator-id (#PCDATA)>
<!ELEMENT supported-browser-id (#PCDATA)>
<!ELEMENT test-suite-id (#PCDATA)>
<!ELEMENT suite-id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT jira-issue (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT browser-type (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT role (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT class-name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT runmode (#PCDATA)>
<!ELEMENT success (#PCDATA)>
<!ELEMENT message (#PCDATA)>
<!ELEMENT start-time (#PCDATA)>
<!ELEMENT end-time (#PCDATA)>
<!ELEMENT user-name (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT locator-type (#PCDATA)>
<!ELEMENT node-ip (#PCDATA)>
<!ELEMENT node-port (#PCDATA)>
<!ELEMENT platform (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT install-dir (#PCDATA)>
<!ELEMENT selenium-server (#PCDATA)>
<!ELEMENT browser (#PCDATA)>

=== caterpillerGopher/gopher/gopher/src/test/resources/com/echostar/gopher/persist/util/GopherDataIngest_Test/testElementLocator.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gopher-data SYSTEM "gopher-data.dtd">
<gopher-data>
	<test-class>
		<id>a class id</id>
		<name>a class name</name>
		<version>1.0</version>
		<class-name>a class name</class-name>
		<description>a description</description>
		<runmode>Y</runmode>
		<jira-issue>41</jira-issue>
    </test-class>
	<test-case>
		<id>case 1</id>
		<name>case 1</name>
		<version>1.0</version>
		<runmode>Y</runmode>
		<test-class-id>a class id</test-class-id>
		<element-locator-id>locator 1</element-locator-id>
	</test-case>
	<test-case>
		<id>case 2</id>
		<name>case 2</name>
		<version>1.0</version>
		<runmode>Y</runmode>
		<test-class-id>a class id</test-class-id>
		<element-locator-id>locator 1</element-locator-id>
		<element-locator-id>locator 2</element-locator-id>
	</test-case>
	<element-locator>
		<id>locator 1</id>
		<locator-type>XPATH</locator-type>
		<name>locator 1</name>
		<value>a locator value</value>
		<description>a locator description</description>
	</element-locator>
	<element-locator>
		<id>locator 2</id>
		<locator-type>XPATH</locator-type>
		<name>locator 2</name>
		<value>another locator value</value>
		<description>another locator description</description>
	</element-locator>
</gopher-data>

=== caterpillerGopher/gopher/gopher/src/test/resources/ingest/shekhar/TestNodes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gopher-data SYSTEM "gopher-data.dtd">
<!--
test-nodes for Shekhar
-->
<gopher-data>
	<test-node>
		<id>10</id>
		<!-- Use default
		<node-ip>10.79.84.196</node-ip>
		-->
		<node-port>5557</node-port>
		<platform>WIN7</platform>
		<user-name>gopher</user-name>
		<!--
		<password></password>
		-->
		<install-dir>C:\\JARnDRIVER</install-dir>
		<selenium-server>selenium-server-standalone-2.44.0.jar</selenium-server>
		<supported-browser-id>0</supported-browser-id>
		<!--
		<supported-browser-id>1</supported-browser-id>
		<supported-browser-id>2</supported-browser-id>
		<supported-browser-id>3</supported-browser-id>
		-->
	</test-node>
	<!--
	<test-node>
		<id>11</id>
		<node-ip>10.79.82.152</node-ip>
		<node-port>5557</node-port>
		<platform>WIN7</platform>
		<user-name>gopher</user-name>
		<password></password>
		<install-dir>C:\\JARnDRIVER</install-dir>
		<selenium-server>selenium-server-standalone-2.44.0.jar</selenium-server>
		<supported-browser-id>1</supported-browser-id>
		<supported-browser-id>0</supported-browser-id>
		<supported-browser-id>2</supported-browser-id>
		<supported-browser-id>3</supported-browser-id>
	</test-node>
	-->
</gopher-data>

=== caterpillerGopher/gopher/gopher/src/test/resources/com/echostar/gopher/persist/util/GopherDataIngest_Test/testTestData.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gopher-data SYSTEM "gopher-data.dtd">
<gopher-data>
	<test-class>
		<id>a class id</id>
		<name>a class name</name>
		<version>1.0</version>
		<class-name>a class name</class-name>
		<description>a description</description>
		<runmode>Y</runmode>
		<jira-issue>41</jira-issue>
		<test-data-type-id>test data type 1</test-data-type-id>
		<test-data-type-id>test data type 2</test-data-type-id>
    </test-class>
    <test-data-type>
        <id>test data type 1</id>
        <name>test data type 1</name>
        <type>STRING</type>
        <role>LABEL</role>
    </test-data-type>
    <test-data-type>
        <id>test data type 2</id>
        <name>test data type 2</name>
        <type>STRING</type>
        <role>LABEL</role>
    </test-data-type>
	<test-case>
		<id>case 1</id>
		<name>case 1</name>
		<version>1.0</version>
		<runmode>Y</runmode>
		<test-class-id>a class id</test-class-id>
		<test-data-id>test data id 1</test-data-id>
	</test-case>
	<test-case>
		<id>case 2</id>
		<name>case 2</name>
		<version>1.0</version>
		<runmode>Y</runmode>
		<test-class-id>a class id</test-class-id>
        <test-data-id>test data id 1</test-data-id>
        <test-data-id>test data id 2</test-data-id>
	</test-case>
    <test-data>
        <id>test data id 1</id>
        <value>test data 1</value>
        <test-data-type-id>test data type 1</test-data-type-id>
    </test-data>
    <test-data>
        <id>test data id 2</id>
        <value>test data 2</value>
        <test-data-type-id>test data type 2</test-data-type-id>
    </test-data>
</gopher-data>

=== caterpillerGopher/gopher/gopher/src/test/resources/ingest/greg/Browsers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gopher-data SYSTEM "gopher-data.dtd">
<!--
All supported-browsers
-->
<gopher-data>
	<supported-browser>
		<id>0</id>
		<name>Firefox</name>
		<browser-type>FIREFOX</browser-type>
	</supported-browser>
	<supported-browser>
		<id>1</id>
		<name>IE</name>
		<browser-type>IEXPLORE</browser-type>
	</supported-browser>
	<supported-browser>
		<id>2</id>
		<name>Chrome</name>
		<browser-type>CHROME</browser-type>
	</supported-browser>
	<supported-browser>
		<id>3</id>
		<name>Safari</name>
		<browser-type>SAFARI</browser-type>
	</supported-browser>
</gopher-data>
